name: Release Foot (Git) Debian Package

permissions:
  contents: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '15 9 */17 * *'

jobs:
  release-foot:
    uses: ./.github/workflows/reusable.yml
    with:
      containerfile: pkgs/foot-git.Containerfile
      package_name: foot-git
      origin: jumpyvi
      label: FootGit-Deb
      suite: stable
      codename: stable
      architecture: amd64
      component: main
      deploy_on: gh-pages
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_EMAIL: ${{ secrets.GPG_EMAIL }}